### ISSUE TITLE
How to make the site accessible to the external networks?

### ISSUE THREAD

**Issue by NelsonGahima** [rtCamp/Frappe-Manager#245]
**Description**
How to make a site accessible to the external networks?

**Use Case**
I want to make my site called "site.localhost" installed on a remote linux server accessible to the external networks via my server's public IP address

**Expected Behavior**
to be able to access my site outside the server's network by using <server_ip>:<port_number> format

**Current Behavior (if applicable)**
i only access my site on my server by browsing http://site.localhost

**Comment by victorarocha** [comment]
Hello NelsonGahima,

What you need is a reverse proxy. You can setup nginx for this purpose.

regards.

**Comment by NelsonGahima** [comment]
Thank you @victorarocha It worked

**Comment by meichthys** [comment]
@NelsonGahima Can you explain what you changed?

**Comment by NelsonGahima** [comment]
I set up an Nginx reverse proxy to make the container site's IP address (for example: 10.1.0.3:80) accessible via the host IP.

Here is how my Ngnix config looks:

```
server {
    listen <host_port>;

    server_name <host_IP>;

    location / {
        proxy_pass http://10.1.0.3:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

My site is now accessible through ```<host_IP>:<host_port>```

I hope this is clear. 

Thank you

**Comment by meichthys** [comment]
Thanks for following up so quickly.

**Comment by NelsonGahima** [comment]
It is my pleasure.

**Comment by Hamza5** [comment]
I have found a different solution that I have tested on WSL:
1. Find the file `\\wsl.localhost\Ubuntu\home\<username>\frappe\sites\<bench_name.localhost>\docker-compose.yml` and open it in a text editor.
2. Find the `nginx`section:
```yml
nginx:
    image: ghcr.io/rtcamp/frappe-manager-nginx:v0.16.1
    container_name: fm__<bench_name>_localhost__nginx
    user: 1000:1000
    environment:
      SITENAME: <bench-name>.localhost
      VIRTUAL_HOST: <bench-name>.localhost
      VIRTUAL_PORT: 80
      HSTS: off
    volumes:
    - ./workspace:/workspace
    - ./configs/nginx/conf:/etc/nginx
    - ./configs/nginx/logs:/var/log/nginx
    - ./configs/nginx/cache:/var/cache/nginx
    - ./configs/nginx/run:/var/run
    - ./configs/nginx/html:/usr/share/nginx/html
    expose:
    - 80
    networks:
      site-network:
        aliases:
        - <bench-name>.localhost
      global-frontend-network: 
```
3. Change `VIRTUAL_HOST` to include the host IP or address:
```
VIRTUAL_HOST: <bench-name>.localhost, 192.168.1.10
```
4. After that, run `fm stop <bench-name>` then `fm start <bench-name>`
