### ISSUE TITLE
How to Expose MariaDB Port in Frappe Manager for Replication Setup?

### ISSUE THREAD

**Issue by Eshwarnani74** [rtCamp/Frappe-Manager#261]
### Description

I am using Frappe Manager (v0.16.0) to manage my Frappe/ERPNext instance, and I would like to set up MariaDB replication. However, I can't find documentation on how to expose the MariaDB port (default 3306) from the Docker container to allow external replication connections.

### What I Need

- How can I expose MariaDB's port using Frappe Manager?
- Is there a recommended way to do this while keeping the container secure?
- Can this be done via the `fm` CLI or do I need to manually edit Docker configurations?

### Setup Info

- **Frappe Manager Version:** 0.16.0  
- **Host OS:** Ubuntu 24.04.2 
- **MariaDB Container Used By:** Frappe/ERPNext via Frappe Manager  
- **Goal:** Enable master/slave or primary/replica MariaDB replication

### Additional Notes

I understand opening DB ports can introduce security concerns. I'm planning to restrict access to a specific IP using firewall rules.

Thanks in advance for your help!

**Comment by Xieyt** [comment]
You will have to manually edit the docker compose file, `fm` doesn't provide any functionality regarding this.
<details>
  <summary>how to (if needed)</summary>

- Edit fm `global-db` service in compose file at:  `~/frappe/services/docker-compose.yml`
- Add the ports configuration to the `global-db` service:
  ```yaml
  services:
    global-db:
      # ... existing configuration ...
      ports:
        - "127.0.0.1:3306:3306" # expose to localhost only
      #           or
        - "0.0.0.0:3306:3306" # expose to all interface
      #           or
        - 3306:3306 # expose to all interface
      #           or
        - "127.0.0.1:3307:3306" # custom port mapping
      # ... rest of configuration ...
  ```
- run command: `docker compose -f ~/frappe/services/docker-compose.yml up -d`

</details>
